### ISSUE TITLE
Using in navigation bar ?

### ISSUE THREAD

**Issue by nahouto** [paul1893/PBTutorialManager#3]
Hi Paul,

Thank you for this easy-to-use library.

How can I use it for navigation bar item ? (which does not inherit from UIView)

I used `self.navigationController?.navigationBar.subviews[3]` but the hole appears a little too high.
I tried to play with bottomMargin etc... without success...

Thank you again.

**Comment by paul1893** [comment]
Hi,

Unfortunatly I didn't think to manage & test with navigation bar when I designed this library. A workaround that works is to build a fake target with a fake UIView.

``` swift
let myFakeView = UIView(frame: CGRectMake(estimatedX, estimatedY, weight, height));
let target = Target(view:myFakeView)
            .withArrow(true)
            .heightArrow(50)
            .widthArrow(25)
            .position(.Bottom)
            .message("Undo")
            .shape(.RoundedRect)
            .breakPoint(true)

let tutorialManager = TutorialManager(parentView: self.view)
tutorialManager.addTarget(target)
tutorialManager.fireTargets()
```

Anyway Thanks for the feedback this is definitely something I will looking for when I will update the lib.
![s1](https://cloud.githubusercontent.com/assets/10085515/19160941/255e264a-8bf2-11e6-9402-311d1de7a140.png)
![s2](https://cloud.githubusercontent.com/assets/10085515/19160947/2752fe8a-8bf2-11e6-84bf-0a7fef0c5053.png)

**Comment by nahouto** [comment]
Thanks, I will test this idea...

**Comment by nahouto** [comment]
I did not manage to reproduce what you show here : 
1. The hole appears under the navigation bar (it is masked by the navigation bar)
2. The hole seems misplaced (below the target view)

For the problem 1. , I have to set the navigationController.view as parentView.

For the problem 2, I did'nt found any solution.

Note : I have both a UITabBarController and a UINavigationController

**Comment by paul1893** [comment]
Hi,

_Problem 1_: Ok good job so now it's working ? (If not: May be navigation bar translucent (or not) property affect the view controller).

_Problem 2_: No idea why it's misplaced for you, if it is just below you can adjust the y position of your fakeView by a negative offset equal to the height of the UINavigationBar. Another supposition: May be the way you design your view in the controller in the Storyboard or may be try to play with [edgesForExtendedLayout](https://developer.apple.com/reference/uikit/uiviewcontroller/1621515-edgesforextendedlayout) on your controller.

**Comment by nahouto** [comment]
Hi, thank you for your answer.
I will ry your suggestions by the en of the week.
