### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by tenaz3** [paul1893/PBTutorialManager#4]
My code is:
```
let targetNameLabel = Target(view: nameLabel).withArrow(true).widthArrow(75).heightArrow(30).position(.Right).shape(JMHoleType.Rect).duration(1.0).message("This is a label").textAlignement(.Left).breakPoint(true)
let tutorialManager = TutorialManager(parentView: self.view)
tutorialManager.addTarget(targetNameLabel)
tutorialManager.fireTargets()
```
It seems that is missing the font REIS-Regular
![screen shot 2016-11-13 at 22 10 17](https://cloud.githubusercontent.com/assets/373955/20248905/7dbbebdc-a9ee-11e6-874a-565e109a594e.png)

**Comment by paul1893** [comment]
Hey tenaz3

Apparently found nil when he tries to get the custom font. Not sure why this error appear, I will looking for it as quickly as possible. Meanwhile you can try to import "REIS-Regular" font or use your own one in your project to fix the issue.

Thanks for sharing this 😉

**Comment by paul1893** [comment]
Ok the issue should be fixed with the 1.0.4 version. Tell me if all is OK for you now. 😉

**Comment by tenaz3** [comment]
Well not really, I'm swift 2.3 and them I got compile errors... but thanks anyway

**Comment by paul1893** [comment]
Yes. I took advantage of this bug fix to update the library with Swift 3 as it is recommended by Apple.
